In [15]:
import pandas as pd 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [19]:
df = pd.read_csv("dataname.csv")
df.head(5)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [21]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [22]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [23]:
df['Review Rating']=df.groupby('Category')['Review Rating'].transform(lambda x :x.fillna(x.median()))
df['Review Rating']

0       3.1
1       3.1
2       3.1
3       3.5
4       2.7
       ...
3895    4.2
3896    4.5
3897    2.9
3898    3.8
3899    3.1
Name: Review Rating, Length: 3900, dtype: float64

In [24]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [25]:
df.columns= df.columns.str.lower()
df.columns= df.columns.str.replace(' ','_')
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [26]:
#create a column age wise .
df['age'].value_counts
labels=['young_adult','adult','middle_age','senior']
df['age_group']=pd.qcut(df['age'],q=4,labels=labels)  #(df['age'],q=4, labels=labels)
df[['age','age_group']]

      age    age_group
0      55   middle_age
1      19  young_adult
2      50   middle_age
3      21  young_adult
4      45   middle_age
...   ...          ...
3895   40        adult
3896   52   middle_age
3897   46   middle_age
3898   44        adult
3899   52   middle_age

[3900 rows x 2 columns]

In [27]:
df['frequency_of_purchases'].value_counts

<bound method IndexOpsMixin.value_counts of 0       Fortnightly
1       Fortnightly
2            Weekly
3            Weekly
4          Annually
           ...
3895         Weekly
3896      Bi-Weekly
3897      Quarterly
3898         Weekly
3899      Quarterly
Name: frequency_of_purchases, Length: 3900, dtype: str>

In [28]:
# create columns purchase frequency days : 
days={
      'Fortnightly':14,
      'Weekly':7,
      'Monthly':30,
      'Quarterly':90,
      'Bi-weekly':14,
      'Annually':365,
      'Every 3 months':90
}
df['purchase_frequency_days'] = df['frequency_of_purchases'].str.lower()
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(days)

df[['frequency_of_purchases','purchase_frequency_days']]

     frequency_of_purchases  purchase_frequency_days
0               Fortnightly                     14.0
1               Fortnightly                     14.0
2                    Weekly                      7.0
3                    Weekly                      7.0
4                  Annually                    365.0
...                     ...                      ...
3895                 Weekly                      7.0
3896              Bi-Weekly                      NaN
3897              Quarterly                     90.0
3898                 Weekly                      7.0
3899              Quarterly                     90.0

[3900 rows x 2 columns]

In [29]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [30]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'age_group',
       'purchase_frequency_days'],
      dtype='str')

In [31]:
df=df.drop('promo_code_used',axis=1)

In [32]:
pip install psycopg2

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2 in c:\users\samrudhi\appdata\roaming\python\python313\site-packages (2.9.11)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~umpy (C:\Users\SAMRUDHI\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~umpy (C:\Users\SAMRUDHI\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~umpy (C:\Users\SAMRUDHI\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~umpy (C:\Users\SAMRUDHI\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~umpy (C:\Users\SAMRUDHI\AppData\Roaming\Python\Python313\site-packages)

[notice] A new release of pip is available: 24.3.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [33]:
pip install sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in c:\users\samrudhi\appdata\roaming\python\python313\site-packages (2.0.40)
Requirement already satisfied: greenlet>=1 in c:\users\samrudhi\appdata\roaming\python\python313\site-packages (from sqlalchemy) (3.2.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\samrudhi\appdata\roaming\python\python313\site-packages (from sqlalchemy) (4.13.2)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~umpy (C:\Users\SAMRUDHI\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~umpy (C:\Users\SAMRUDHI\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~umpy (C:\Users\SAMRUDHI\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~umpy (C:\Users\SAMRUDHI\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~umpy (C:\Users\SAMRUDHI\AppData\Roaming\Python\Python313\site-packages)

[notice] A new release of pip is available: 24.3.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [34]:
pip install psycopg2.binary sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2.binary in c:\users\samrudhi\appdata\roaming\python\python313\site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in c:\users\samrudhi\appdata\roaming\python\python313\site-packages (2.0.40)
Requirement already satisfied: greenlet>=1 in c:\users\samrudhi\appdata\roaming\python\python313\site-packages (from sqlalchemy) (3.2.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\samrudhi\appdata\roaming\python\python313\site-packages (from sqlalchemy) (4.13.2)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~umpy (C:\Users\SAMRUDHI\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~umpy (C:\Users\SAMRUDHI\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~umpy (C:\Users\SAMRUDHI\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~umpy (C:\Users\SAMRUDHI\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~umpy (C:\Users\SAMRUDHI\AppData\Roaming\Python\Python313\site-packages)

[notice] A new release of pip is available: 24.3.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [35]:
from sqlalchemy import create_engine
username ='postgres'
password= "1012"
host='localhost'
port="5432"
database = 'dataname'
engine= create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")
table_name='customer'
df.to_sql(table_name,engine,if_exists='replace',index=False)
print(f"data sucessfully loaded into table '{table_name}' in database '{database}'.")

data sucessfully loaded into table 'customer' in database 'dataname'.